<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * About us view script
 *
 * @package    Application
 */

$this->headTitle('Impressum');
$this->pageTitle('Impressum und rechtliche Hinweise');
?>
<h3>Angaben gem&auml;&szlig; &sect; 5 TMG:</h3>

<p>Travello GmbH<br/>
    An der Eiche 15<br/>
    25421 Pinneberg</p>

<h3>Vertreten durch:</h3>

<p>Herr Ralf Eggert</p>

<h3>Kontakt:</h3>

<p>Telefon: +49 (0) 4101 8529401<br/>
    Telefax: +49 (0) 4101 8529402<br/>
    E-Mail: <a href="mailto:info@ralfeggert.de">info@ralfeggert.de</a></p>

<h3>Registereintrag:</h3>

<p>Eintragung im Handelsregister<br/>
    Registergericht: Amtsgericht Pinneberg<br/>
    Registernummer: HRB 6112 PI</p>

<h3>Umsatzsteuer-ID:</h3>

<p>Umsatzsteuer-Identifikationsnummer gem&auml;&szlig; &sect;27 a Umsatzsteuergesetz:<br/>
    DE240723324</p>