<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * About us view script
 *
 * @package    Application
 */

$this->headTitle('Über uns');
$this->pageTitle('Wir stellen uns vor');
?>
<p>Über uns</p>

