<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Customer
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

use Customer\Entity\CustomerEntity;

/**
 * Index view script
 *
 * @package    Customer
 */

?>
<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>ID</th>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>Anschrift</th>
        <th>Land</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->customerList as $customerEntity) : /* @var $customerEntity CustomerEntity */ ?>
        <tr>
            <td><?php echo $customerEntity->getId(); ?></td>
            <td><?php echo $customerEntity->getFirstname(); ?></td>
            <td><?php echo $customerEntity->getLastname(); ?></td>
            <td><?php echo $customerEntity->getStreet() . ', ' . $customerEntity->getPostcode() . ' ' . $customerEntity->getCity(); ?></td>
            <td><?php echo $customerEntity->getCountry(); ?></td>
            <td>&nbsp;</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<hr />
<a href="<?php echo $this->url('home'); ?>" class="btn btn-success">Übersicht</a>

