<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Customer
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

use Customer\Entity\CustomerEntity;

/**
 * Show view script
 *
 * @package    Customer
 */

$customerEntity = $this->customerEntity; /* @var $customerEntity CustomerEntity */

?>
<table class="table table-striped table-bordered table-hover">
    <tbody>
    <tr>
        <th>ID</th>
        <td><?php echo $customerEntity->getId(); ?></td>
    </tr>
    <tr>
        <th>Vorname</th>
        <td><?php echo $customerEntity->getFirstname(); ?></td>
    </tr>
    <tr>
        <th>Nachname</th>
        <td><?php echo $customerEntity->getLastname(); ?></td>
    </tr>
    <tr>
        <th>Anschrift</th>
        <td><?php echo $customerEntity->getStreet() . ', ' . $customerEntity->getPostcode() . ' ' . $customerEntity->getCity(); ?></td>
    </tr>
    <tr>
        <th>Land</th>
        <td><?php echo $customerEntity->getCountry(); ?></td>
    </tr>
    </tbody>
</table>
<hr />
<a href="<?php echo $this->url('customer'); ?>" class="btn btn-success">Kundenliste</a>
