<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Header view script
 *
 * @package    Application
 */

?>
<div class="top_line"></div>
<header>
    <div class="container">
        <div class="row">
            <div class="span12">
                <div class="logo">
                    <a href="/"><img alt="Zend Framework 2" title="Zend Framework 2" src="/img/zf2-logo.png"></a>
                </div>
                <div class="logo-right">
                    <img alt="International PHP Conference 2013" title="International PHP Conference 2013" src="/img/ipc2013-logo.png">
                </div>
                <div class="logo-text">
                    <h2><a href="/">Unit-Testing einer ZF2 Anwendung</a></h2>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="navbar">
            <div class="navbar-inner">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li><a href="<?php echo $this->url('home'); ?>">Startseite</a></li>
                        <li><a href="<?php echo $this->url('imprint'); ?>">Impressum</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>

