<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * Sidebar view script
 *
 * @package    Application
 */

$url = $this->url(null, array(), true);
?>
<div class="pull-center well">
    Box 1
</div>
<br/>
<div class="pull-center well">
    Box 2
</div>
