<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'application/index/index'   => __DIR__ . '/application/index/index.phtml',
    'application/about/index'   => __DIR__ . '/application/about/index.phtml',
    'application/about/imprint' => __DIR__ . '/application/about/imprint.phtml',
    'template_map'              => __DIR__ . '/template_map.php',
    'layout/header'             => __DIR__ . '/layout/header.phtml',
    'layout/footer'             => __DIR__ . '/layout/footer.phtml',
    'layout/layout'             => __DIR__ . '/layout/layout.phtml',
    'layout/sidebar'            => __DIR__ . '/layout/sidebar.phtml',
    'error/index'               => __DIR__ . '/error/index.phtml',
    'error/404'                 => __DIR__ . '/error/404.phtml',
);
