<?php
/**
 * Unit-Testing einer Zend Framework 2 Anwendung
 *
 * Zend Framework Session auf der International PHP Conference 2013 in München
 *
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Ralf Eggert <r.eggert@travello.de>
 * @link       http://www.ralfeggert.de/
 */

/**
 * namespace definition and usage
 */

/**
 * Index view script
 *
 * @package    Application
 */

$this->pageTitle('Herzlich Willkommen!');

?>
<div class="hero-unit">
    <h1>Unit-Testing einer ZF2 Anwendung</h1>

    <h2>International PHP Conference 2013 in München</h2>
    <p>Alle Beispiele, die in der Session gezeigt werden, sind mit Hilfe dieses Beispielprojektes nachvollziehbar. Sie können es gerne als
        Basis für eigene Projekte nutzen.</p>
</div>

